let report=INITIAL, selectedCoin=INITIAL?.coins?.[0]?.symbol||'BTC', selectedMetric=3, view='overview';
const $=id=>document.getElementById(id);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={ok:'Current',unavailable:'Unavailable',stale:'Stale',model:'Model',scenario:'Scenario',external:'Imported'};
const badge=s=>`<span class="badge ${escape(s)}">${escape(labels[s]||s)}</span>`;
const number=n=>typeof n==='number'?new Intl.NumberFormat('en-US',{maximumFractionDigits:Math.abs(n)<1?5:3}).format(n):String(n??'—');
function format(m,detail=false){if(m.value===null||m.value===undefined)return '—';if(typeof m.value==='object')return detail?JSON.stringify(m.value,null,2):Array.isArray(m.value)?m.value.map(number).join(' · '):'View components →';if(typeof m.value==='boolean')return m.value?'Yes':'No';if(typeof m.value==='number'&&m.unit.includes('fraction'))return `${number(m.value*100)}%`;return number(m.value)}
function rowFor(coin,id){return coin.metrics.find(m=>m.id===id)}
function spark(prices){if(prices.length<2)return '';let min=Math.min(...prices),max=Math.max(...prices),range=max-min||1;let points=prices.map((p,i)=>`${(i*160/(prices.length-1)).toFixed(1)},${(32-(p-min)/range*28).toFixed(1)}`).join(' ');return `<svg class="spark" viewBox="0 0 160 36" preserveAspectRatio="none" role="img" aria-label="Last 30 daily closes"><polyline points="${points}" fill="none" stroke="${prices.at(-1)>=prices[0]?'#8ae7cf':'#f58c97'}" stroke-width="1.3"/></svg>`}
function showView(name){view=name;document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==name);document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));let names={overview:'Market overview',metrics:'Metric explorer',handbook:'Practical handbook',sources:'Data health'};$('sectionName').textContent=names[name];$('viewTitle').innerHTML=({overview:'Read the market.<br><span>Know the evidence.</span>',metrics:'Every metric.<br><span>Its source. Its limits.</span>',handbook:'A stronger process.<br><span>One check at a time.</span>',sources:'Trust starts<br><span>with the source.</span>'})[name];$('viewSubtitle').textContent=({overview:'One scan. Every coin. All 136 metrics, with the context behind each number.',metrics:'Explore an indicator to see its formula, interpretation and actual observation.',handbook:'Forty independent checks from the Crypto Investor Master Handbook.',sources:'Freshness, coverage and provider failures remain visible.'})[name];if(name==='metrics')renderMetrics()}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
function render(){if(!report)return;const demo=report.mode.startsWith('DEMO'),count=report.coins.length,total=count*136,current=report.coins.reduce((n,c)=>n+(c.coverage.ok||0),0),missing=report.coins.reduce((n,c)=>n+(c.coverage.unavailable||0),0);const age=(Date.now()-new Date(report.generated_at).getTime())/1000;
 $('notice').className='notice'+(demo?' demo':age>Math.max(600,report.interval_seconds*2)?' error':'');$('notice').textContent=demo?'DEMONSTRATION · All numeric examples are synthetic fixtures. This is a design and functionality preview, not a market report.':age>Math.max(600,report.interval_seconds*2)?'REPORT OUT OF DATE · Scan is overdue. Inspect timestamps and Data health before using this snapshot.':`SOURCE-AWARE REPORT · ${report.interval_seconds/60} min publication timer; individual observations retain their own source timestamps.`;
 $('scanTime').textContent=report.scan_boundary.slice(0,16).replace('T',' ')+' UTC';$('scanDetail').textContent=`${report.duration_seconds}s scan · ${report.lookback_days}d research window`;$('connection').textContent=LIVE?'Auto-refresh · 30s':'Saved snapshot';$('download').disabled=false;
 const stats=[['ASSETS IN WATCHLIST',String(count).padStart(2,'0'),'BTC / ETH benchmark context'],['METRICS PER COIN','136',`${total.toLocaleString()} records in this scan`],['CURRENT COVERAGE',`${Math.round(current/total*100)}%`,`${current} observations / calculations · not confidence`],['UNAVAILABLE',missing.toLocaleString(),'Missing evidence remains visible']];
 $('stats').innerHTML=stats.map((s,i)=>`<div class="stat ${i===2?'accent':''}"><div class="stat-label">${s[0]}</div><strong>${s[1]}</strong><small>${escape(s[2])}</small></div>`).join('');
 $('cards').innerHTML=report.coins.map(c=>{let change=rowFor(c,34),beta=rowFor(c,3),q=c.quote;return `<button class="coin-card" data-coin="${escape(c.symbol)}" aria-label="Explore ${escape(c.symbol)} metrics"><div class="coin-top"><span class="coin-icon">${escape(c.symbol[0])}</span><b>${escape(c.symbol)}</b><small>${q&&(Date.now()-new Date(q.as_of).getTime())>120000?'STALE':'USD'}</small></div><div class="coin-price">${q?'$'+new Intl.NumberFormat('en-US',{maximumFractionDigits:q.price<10?4:2}).format(q.price):'Unavailable'}</div><div class="coin-change ${change.value>=0?'up':'down'}">${change.status==='ok'?(change.value>=0?'+':'')+number(change.value*100)+'%':'—'} <span class="muted">daily close</span></div>${spark(c.sparkline)}<div class="muted" style="font-size:8px;margin-bottom:7px">${q?'Quote '+escape(q.as_of.slice(11,19))+' UTC':'No quote'}</div><div class="coin-bottom"><span>β ${beta.status==='ok'?number(beta.value):'—'}</span><span>${c.coverage.ok||0}/136 current</span></div></button>`}).join('');
 $('cards').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selectedCoin=b.dataset.coin;$('coinSelect').value=selectedCoin;showView('metrics')}));
 const families=[['Exposure & connection',1,22],['Model explanation',23,33],['Returns & path risk',34,67],['Time-series diagnostics',68,80],['Liquidity & execution',81,93],['Derivatives & options',94,108],['Settlement & supply',109,128],['Market participation',129,136]];
 $('evidence').innerHTML=families.map(([name,start,end])=>{let den=(end-start+1)*count,ok=report.coins.reduce((n,c)=>n+c.metrics.filter(m=>m.id>=start&&m.id<=end&&m.status==='ok').length,0);return `<div class="evidence-row"><span>${name}</span><div class="bar"><i style="width:${ok/den*100}%"></i></div><small>${ok}/${den}</small></div>`}).join('');
 const chosen=report.coins.find(c=>c.symbol===selectedCoin)||report.coins[0];$('checks').innerHTML=chosen.checks.slice(0,4).map(c=>`<div class="check"><strong>${escape(c.name)} · ${escape(chosen.symbol)}</strong><span class="value">${escape(c.value)}</span><p>${escape(c.note)}</p></div>`).join('');
 $('coinSelect').innerHTML=report.coins.map(c=>`<option ${c.symbol===selectedCoin?'selected':''}>${escape(c.symbol)}</option>`).join('');
 $('providerRows').innerHTML=Object.entries(report.provider_health).map(([host,v])=>`<div class="provider"><div>${escape(host)}<div class="muted">${escape(v.checked_at)} ${escape(v.reason||'')}</div></div>${badge(v.status)}</div>`).join('')||'<p class="muted">No provider connections in this demonstration.</p>';
 $('providerRows').innerHTML+=`<div class="provider"><span>Kraken WebSocket</span><span class="muted">${escape(report.stream_status)}</span></div>`;
 $('issueRows').innerHTML=[...report.issues.map(i=>`${i.coin} / ${i.feed}: ${i.reason}`),...report.external_errors].map(x=>`<div class="issue">${escape(x)}</div>`).join('')||'<p class="muted">No collection errors recorded. Metric-specific missing-data reasons remain in the explorer.</p>';
 if(view==='metrics')renderMetrics();}
function renderMetrics(){let coin=report?.coins.find(c=>c.symbol===selectedCoin),query=$('search').value.trim().toLowerCase(),state=$('statusSelect').value;
 if(!coin){$('metricCount').textContent=`${selectedCoin} · waiting for a completed scan`;$('metricRows').innerHTML='<tr><td colspan="3">This coin has no data in the latest report. Add it in Telegram → Controls → Coins, then wait for a scan.</td></tr>';$('inspector').innerHTML=`<h2>${escape(selectedCoin)} / Metric ${selectedMetric}</h2><p>No completed observation for this coin. Other coins are not substituted.</p>`;if(!$('coinSelect').querySelector(`option[value="${selectedCoin}"]`))$('coinSelect').insertAdjacentHTML('beforeend',`<option value="${escape(selectedCoin)}">${escape(selectedCoin)} (pending)</option>`);$('coinSelect').value=selectedCoin;return;}
 $('coinSelect').value=selectedCoin;
 const matches=coin.metrics.filter(m=>{let def=report.catalog.find(c=>c.id===m.id);return (state==='all'||m.status===state)&&(!query||`${m.id} ${def.name} ${def.dependency}`.toLowerCase().includes(query))});
 $('metricCount').textContent=`${matches.length} of 136 indicators · ${coin.symbol}`;
 $('metricRows').innerHTML=matches.map(m=>`<tr class="${m.id===selectedMetric?'selected':''}"><td><button data-id="${m.id}"><span class="id">${String(m.id).padStart(3,'0')}</span>${escape(report.catalog.find(d=>d.id===m.id).name)}</button></td><td><span class="num">${escape(format(m))}</span></td><td>${badge(m.status)}</td></tr>`).join('')||'<tr><td colspan="3">No indicators match these filters.</td></tr>';
 $('metricRows').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selectedMetric=Number(b.dataset.id);renderMetrics()}));
 let m=rowFor(coin,selectedMetric),def=report.catalog.find(d=>d.id===selectedMetric);
 $('inspector').innerHTML=`<div class="eyebrow">${escape(coin.symbol)} / METRIC ${String(m.id).padStart(3,'0')}</div><h2>${escape(def.name)}</h2>${badge(m.status)}<div class="big-value">${escape(format(m,true))}</div><span class="muted">${escape(m.unit)}</span><h3>Observation notes</h3><p>${escape(m.note)}</p><h3>What it means</h3><p>${escape(def.description)}</p><h3>Book formula / method</h3><pre>${escape(def.method)}</pre><h3>Book illustration (not this scan)</h3><p>${escape(def.interpretation)}</p><dl><dt>SOURCE</dt><dd>${escape(m.source||'No connected eligible source')}</dd><dt>AS OF / FREQUENCY</dt><dd>${escape(m.as_of||'Unavailable')} · ${escape(m.frequency||'—')}</dd><dt>SAMPLE</dt><dd>${escape(m.sample??'Not supplied')}</dd><dt>BOOK REFERENCE</dt><dd>Reading the Crypto Market, p. ${def.page}</dd></dl>`;
}
['coinSelect','statusSelect'].forEach(id=>$(id).addEventListener('change',()=>{selectedCoin=$('coinSelect').value;renderMetrics()}));$('search').addEventListener('input',renderMetrics);
$('handbookCards').innerHTML=HANDBOOK.map(h=>`<article class="panel handbook-card"><div class="eyebrow">${h.id} · MANUAL CHECK</div><h3>${escape(h.name)}</h3><p>${escape(h.description)}</p><div class="question">${escape(h.check)}</div><p>Master Handbook · p. ${h.page}</p></article>`).join('');
$('download').addEventListener('click',()=>{if(LIVE){window.location.href='/reports/latest.zip';return;}let blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`atlas-136-${report.scan_id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
if(!LIVE)$('download').textContent='↓ Export JSON';
async function refresh(){try{const response=await fetch('/api/report',{cache:'no-store',headers:report?.generated_at?{'If-None-Match':'"'+report.generated_at+'"'}:{}});if(response.status===503)return;if(response.status===304){render();return;}if(!response.ok)throw new Error('HTTP '+response.status);report=await response.json();render()}catch(error){$('connection').textContent='Refresh failed';$('notice').className='notice error';$('notice').textContent='CONNECTION LOST · Displaying the last saved scan. Its timestamps remain unchanged.'}}
render();if(LIVE){if(!report)refresh();setInterval(refresh,30000)}
