const $=id=>document.getElementById(id);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=value=>typeof value==='number'&&Number.isFinite(value)?new Intl.NumberFormat('en-IN',{maximumSignificantDigits:7}).format(value):'N/A';
const ist=value=>{if(!value)return 'Unavailable';const d=new Date(value);return Number.isNaN(+d)?'Unavailable':new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(d)+' IST'};
const badge=s=>`<span class="pill ${['ok','stale','unavailable','model','external'].includes(s)?s:''}">${escape(s||'unavailable')}</span>`;
const value=v=>v===null||v===undefined?'Unavailable':typeof v==='object'?Object.entries(v).map(([k,x])=>escape(k.replaceAll('_',' '))+': '+escape(typeof x==='number'?n(x):JSON.stringify(x))).join('<br>'):escape(n(v));
const period={'5m':300,'1h':3600,'4h':14400,'1d':86400};
function quoteState(q){return q&&Date.now()-new Date(q.as_of)> (q.status==='closed candle'?420:180)*1000?'stale':q?.status;}
const venues=['okx','bybit','bitget','gate','mexc','kucoin','bingx','htx','phemex','coinex'];
let report=INITIAL,view='overview',selectedCoin=INITIAL?.coins?.[0]?.symbol||'BTC',tf='1d',selectedMetric=3,loopState=null;
function status(row){if(!row)return 'unavailable';if(!['ok','model','external'].includes(row.status)||!row.as_of)return row.status;let ttl=row.frequency==='native snapshot'?600:(period[row.frequency]||86400)+(row.frequency==='1d'?7200:120);return Date.now()-new Date(row.as_of).getTime()>ttl*1000?'stale':row.status;}
function rowsFor(c,timeframe){return c?.metric_frames?.[timeframe]||(timeframe==='1d'?c?.metrics:[])||[];}
function metric(c,id,timeframe='1d'){return rowsFor(c,timeframe).find(r=>r.id===id);}
function move(c,timeframe){let row=metric(c,34,timeframe);return status(row)==='ok'?`<span class="${row.value>=0?'positive':'negative'}">${row.value>=0?'+':''}${n(row.value*100)}%</span>`:'N/A';}
function showView(next){view=['overview','technical','metrics','sources','handbook'].includes(next)?next:'overview';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('sectionName').textContent=({overview:'My tracking list',technical:'Technical studies',metrics:'Metric explorer',sources:'Tracking sources',handbook:'Practical handbook'})[view];render();}
function link(){history.replaceState(null,'','#'+new URLSearchParams({view,coin:selectedCoin,tf,metric:String(selectedMetric)}));}
function render(){
 if(!report){$('notice').textContent='First scan is collecting. Check Telegram /status. The dashboard stays available.';return;}
 const demo=report.mode.includes('SYNTHETIC'),old=Date.now()-new Date(report.generated_at)>Math.max(600,report.interval_seconds*2)*1000;
 $('notice').className='notice'+(demo||old?' warning':'');$('notice').textContent=demo?'DEMO - SYNTHETIC DATA. No live prices or funding observations.':old?'OLD REPORT - last completed snapshot shown. Check source timestamps and /status.':'Selected USDT instruments only. Native funding/OI and daily beta retain their own measurement windows.';
 $('scanTime').textContent=ist(report.generated_at);$('scanInfo').textContent=`${report.coins.length} tracked / ${report.max_coins||50} slots | ${report.duration_seconds}s scan | Daily beta: ${report.lookback_days} return lookback`;$('connection').textContent=LIVE?'Refreshes every 30 seconds':'Saved report';
 $('coinSelect').innerHTML=report.coins.map(c=>`<option value="${escape(c.symbol)}">${escape(c.symbol)}</option>`).join('');
 if(!report.coins.some(c=>c.symbol===selectedCoin))$('coinSelect').insertAdjacentHTML('beforeend',`<option value="${escape(selectedCoin)}">${escape(selectedCoin)} (pending)</option>`);
 $('coinSelect').value=selectedCoin;$('technicalTimeframe').value=tf;
 const coin=report.coins.find(c=>c.symbol===selectedCoin),route=coin?.route,q=coin?.quote;
 $('vendorRows').innerHTML=Object.entries(coin?.context||{}).map(([name,c])=>`<h3>${escape(name)}</h3>${badge(c.status)}<p>${escape(c.name||'')} ${c.id!=null?'ID '+escape(c.id):''} ${c.rank!=null?'| Rank '+escape(c.rank):''}</p>${c.market_cap_usdt!=null?'<p>Market cap '+n(c.market_cap_usdt)+' USDT</p>':''}${c.circulating_supply!=null?'<p>Circulating supply '+n(c.circulating_supply)+' tokens</p>':''}<p>${escape((c.matches||[]).map(m=>m.name+' (ID '+m.id+')').join(', '))}</p><p>${ist(c.as_of)}</p><p>${escape(c.note)}</p>`).join('')||'<p>No optional provider context collected. Exchange measurements remain available independently.</p>';
 let b=metric(coin,3),e=metric(coin,4);
 $('instrument').innerHTML=`<div><strong>${escape(selectedCoin)}</strong><small>${route?escape(route.exchange+' / '+route.market+' / '+route.symbol):'Selected instrument unavailable'}</small></div><div><span class="value">${q?n(q.price)+' USDT':'No price'}</span><small>${q?escape(quoteState(q))+' | '+ist(q.as_of):'No eligible observation'}</small></div><div><strong>Beta ${status(b)==='ok'?n(b.value):'N/A'} / ${status(e)==='ok'?n(e.value):'N/A'}</strong><small>BTC / ETH | DAILY ONLY | ${ist(b?.as_of)}</small></div>`;
 $('watchCount').textContent=report.coins.length+' tracked';
 $('watchRows').innerHTML=report.coins.map(c=>{let r=c.route,q=c.quote,b=metric(c,3),e=metric(c,4);return `<tr><td><button data-coin="${escape(c.symbol)}">${escape(c.symbol)}</button><small>${r?escape(r.exchange+' / '+r.market):'No eligible source'}</small></td><td class="num">${q?n(q.price):'N/A'}<small>${q?escape(quoteState(q))+' | '+ist(q.as_of):'Unavailable'}</small></td>${Object.keys(period).map(t=>'<td>'+move(c,t)+'</td>').join('')}<td>${status(b)==='ok'?n(b.value):'N/A'} / ${status(e)==='ok'?n(e.value):'N/A'}</td></tr>`}).join('');
 $('watchRows').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedCoin=b.dataset.coin;showView('technical');link()});
 if(view==='technical')renderTechnical(coin);
 if(view==='metrics')renderMetrics(coin);
 if(view==='sources')renderSources();
 renderControl();
}
function renderTechnical(coin){
 const pack=coin?.technical?.[tf];let opened=new Set([...$('studyCards').querySelectorAll('details[open]')].map(e=>e.dataset.id));
 if(!pack){$('chart').textContent='Waiting for this coin/timeframe; no other instrument is substituted.';$('studyCards').innerHTML='';$('dailyDerivatives').innerHTML='';return;}
 let points=pack.chart||[],line='';if(points.length){let lo=Math.min(...points.map(p=>p.close)),hi=Math.max(...points.map(p=>p.close)),span=hi-lo||hi*.01;line=points.map((p,i)=>`${10+i/(Math.max(1,points.length-1))*780},${135-(p.close-lo)/span*110}`).join(' ');}
 $('chart').innerHTML=`<h3>${escape(selectedCoin)} / ${escape(tf)} closed candles</h3><p>${escape(pack.source||'Unavailable')} | ${pack.bars} bars | Close: ${ist(pack.as_of)}</p>${points.length?`<svg viewBox="0 0 800 155" role="img" aria-label="Last 60 closed USDT prices"><path d="M10 140H790" stroke="#29414f"/><polyline points="${line}" fill="none" stroke="#60dfcb" stroke-width="2"/></svg><p>${ist(points[0].time)} - ${ist(points.at(-1).time)} | Last close ${n(points.at(-1).close)} USDT</p>`:'<p>No closed-candle chart available.</p>'}`;
 $('studyCards').innerHTML=pack.rows.map(r=>`<article class="panel study"><h3>${escape(r.name)}</h3>${badge(status(r))}<div class="value">${value(r.value)}</div><div class="unit">${escape(r.unit)} | ${escape(r.frequency||tf)}</div><p>${escape(r.reading||'')}<br>${ist(r.as_of)}</p><details data-id="${escape(r.id)}" ${opened.has(r.id)?'open':''}><summary>Method &amp; source</summary><p>${escape(r.method)}</p><p>${escape(r.note)}</p><dl><dt>SOURCE</dt><dd>${escape(r.source||'Unavailable')}</dd><dt>HISTORY START / CANDLE STUDIES</dt><dd>${ist(pack.history_start)}</dd></dl></details></article>`).join('');
 const d=coin.derivatives||{};
 $('dailyDerivatives').innerHTML=[['Daily settled funding',d.daily_funding],['Daily open interest',d.daily_oi]].map(([title,r])=>`<article class="panel"><h3>${title}</h3>${badge(r?.status)}<p>${value(r?.value)} ${escape(r?.unit||'')}</p>${r?.change_fraction!=null?'<p>Daily change '+n(r.change_fraction*100)+'%</p>':''}<p>${ist(r?.start)} - ${ist(r?.end)}</p><p>${escape(r?.note||'Historical observations unavailable')}</p></article>`).join('');
}
function renderMetrics(coin){
 const rows=rowsFor(coin,tf),query=$('search').value.toLowerCase(),filter=$('statusSelect').value;
 const matches=rows.filter(r=>{let def=report.catalog.find(d=>d.id===r.id);return (filter==='all'||status(r)===filter)&&(!query||`${r.id} ${def.name}`.toLowerCase().includes(query))});
 $('metricCount').textContent=`${matches.length} / 136 | ${tf}`;
 $('metricRows').innerHTML=matches.map(r=>`<tr class="${r.id===selectedMetric?'selected':''}"><td><button data-id="${r.id}">${r.id}. ${escape(report.catalog.find(d=>d.id===r.id).name)}</button></td><td>${r.value==null?'Unavailable':typeof r.value==='object'?'Components':n(r.value)}</td><td>${badge(status(r))}</td></tr>`).join('')||'<tr><td colspan="3">No matching records for this coin and timeframe.</td></tr>';
 $('metricRows').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedMetric=Number(b.dataset.id);renderMetrics(coin);link()});
 let r=rows.find(r=>r.id===selectedMetric),def=report.catalog.find(d=>d.id===selectedMetric);
 $('inspector').innerHTML=r?`<div class="label">${escape(selectedCoin)} / ${tf} / ${r.id}</div><h2>${escape(def.name)}</h2>${badge(status(r))}<div class="value">${value(r.value)}</div><small>${escape(r.unit)}</small><h3>Calculation notes</h3><p>${escape(r.note)}</p><h3>Book explanation</h3><p>${escape(def.description)}</p><h3>Reference formula</h3><pre>${escape(def.method)}</pre><dl><dt>SOURCE</dt><dd>${escape(r.source||'Unavailable')}</dd><dt>OBSERVED / NATIVE FREQUENCY</dt><dd>${ist(r.as_of)} | ${escape(r.frequency||'unavailable')}</dd><dt>SAMPLE</dt><dd>${r.sample??'Unavailable'}</dd><dt>BOOK PAGE</dt><dd>${def.page}</dd></dl>`:'Select a coin with a completed scan.';
}
function renderSources(){let routing=report.routing||{};
 $('routingInfo').innerHTML=`<h3>Perpetual first. Spot fallback. Your choice.</h3><p>${escape(routing.source||'Configured priority')} | ${ist(routing.as_of)}</p><p>${(routing.order||venues).map(escape).join(' &gt; ')}</p><p>Pin: <b>/route SOL bybit perp</b> | Spot: <b>/route SOL okx spot</b> | Reset: <b>/route SOL auto</b></p><p>Priority is an availability/liquidity preference, not a guarantee of accuracy. Exact base symbols are matched; 1000PEPE and PEPE are not silently treated as the same unit.</p>`;
 $('sourceRows').innerHTML=venues.map(v=>{let health=report.provider_health?.[v],coins=report.coins.filter(c=>c.route?.exchange===v);return `<article class="panel"><h3>${escape(v)}</h3>${badge(health?.status||'not checked')}<p>${coins.length} selected instruments</p><p>${escape(coins.map(c=>c.route.symbol).join(', ')||'No selected route')}</p><p>${health?ist(health.checked_at)+'<br>'+escape(health.reason||''):'No observation in this process'}</p></article>`}).join('');
 $('issueRows').innerHTML=[...report.issues.map(i=>`${i.coin}: ${i.reason}`),...(report.external_errors||[])].map(s=>`<div class="issue">${escape(s)}</div>`).join('')||'<p>No collection errors recorded. Individual unavailable metrics retain their own reasons.</p>';
}
function renderControl(){if(!loopState)return;let s=loopState;$('controlStatus').innerHTML=`<b>${s.ready?(s.paused?'Paused':s.in_progress?'Scanning':'Automatic loop active'):'Settings storage unavailable'}</b> | ${s.coins.length}/${s.max_coins||50} coins | ${s.interval/60} min | ${s.next_scan_at?'Next: '+ist(s.next_scan_at):'No scheduled start'}<br>Manage in Telegram /panel. ${report?.control_revision!==s.revision?'Settings changed; this report is awaiting the next matching scan.':''}`;}
function readLink(){const p=new URLSearchParams(location.hash.slice(1));if(p.get('coin')&&/^[A-Z0-9][A-Z0-9._-]{0,23}$/.test(p.get('coin')))selectedCoin=p.get('coin');if(period[p.get('tf')])tf=p.get('tf');const m=Number(p.get('metric'));if(m>=1&&m<=136)selectedMetric=m;showView(p.get('view')||'overview');}
$('coinSelect').onchange=()=>{selectedCoin=$('coinSelect').value;render();link()};$('technicalTimeframe').onchange=()=>{tf=$('technicalTimeframe').value;render();link()};$('search').oninput=()=>renderMetrics(report?.coins.find(c=>c.symbol===selectedCoin));$('statusSelect').onchange=$('search').oninput;
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{showView(b.dataset.view);link()});
$('handbookCards').innerHTML=HANDBOOK.map(h=>`<article class="panel"><div class="label">${escape(h.id)} | MANUAL CHECK</div><h3>${escape(h.name)}</h3><p>${escape(h.description)}</p><p>${escape(h.check)}</p><small>Master Handbook, page ${h.page}</small></article>`).join('');
$('download').onclick=()=>{if(LIVE){location.href='/reports/latest.zip';return;}const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='atlas-tracking.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
async function refresh(){try{let r=await fetch('/api/report',{cache:'no-store',headers:report?.generated_at?{'If-None-Match':'"'+report.generated_at+'"'}:{}});if(r.status===503)return;if(r.status!==304){if(!r.ok)throw Error('refresh');report=await r.json()}render()}catch(e){$('notice').textContent='Connection lost. Last completed report remains visible; check timestamps.';$('notice').className='notice warning'}}
async function controls(){try{let r=await fetch('/api/control',{cache:'no-store'});if(r.ok){loopState=await r.json();renderControl()}}catch(e){$('controlStatus').textContent='Control status unavailable. Use Telegram /status.'}}
window.addEventListener('hashchange',readLink);readLink();if(LIVE){refresh();controls();setInterval(refresh,30000);setInterval(controls,15000)}
